#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -N fastqc_summary
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS
#PBS -l walltime=2:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -t 1


#Set directories
PROJ=/scratch/lfs/mcintyre/trago
ORIG=/scratch/lfs/mcintyre/trago/original_data/trago-tetraploids
QC=/scratch/lfs/mcintyre/trago/qc_test
DATAIN=$QC/fastqc/fastqc_files
DATAOUT=$QC/fastqc/fastqc_summary
if [ ! -e $DATAOUT ]; then mkdir -p $DATAOUT; fi

STATSOUT=$DATAOUT/files
if [ ! -e $STATSOUT ]; then mkdir -p $STATSOUT; fi

PASSFAIL=/scratch/lfs/mcintyre/qc_pipeline/scripts/fastqc_pass-fail_list_rlb.pl
STATS=/scratch/lfs/mcintyre/qc_pipeline/scripts/fastqc_stats_v2_jmf.pl


echo "Sample_id,basic_stats,base_qual,seq_qual,base_content,base_GC,seq_GC,base_N,seq_length,seq_dup,seq_overrep,kmer,percent_pass" > $DATAOUT/fastqc_pass-fail_summary.csv
cd $DATAIN

for SAMPLE in $( find ./ -maxdepth 1 -type d -print | cut -d'/' -f2)
    do
    FILE=$DATAIN/$SAMPLE/summary.txt
    perl $FASTQC $SAMPLE $FILE  >> $DATAOUT/fastqc_pass-fail_summary.csv
done

for DIR in $( find ./ -maxdepth 1 -type d | cut -f2 -d'/')
    do
    cd $DATAIN/$DIR
    NAME=`basename $DIR _fastqc`
    perl $STATS $NAME $STATSOUT
done
