#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -N homopolymers
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=6gb
#PBS -t 2-37


# Load modules

module load python/2.7.3

#Set directories
PROJ=/scratch/lfs/mcintyre/trago
ORIG=/scratch/lfs/mcintyre/trago/original_data/trago-tetraploids
QC=/scratch/lfs/mcintyre/trago/qc_test
MCPYTHON=/scratch/lfs/mcintyre/python.git

OUTPUT=$QC/homopolymer_files
if [ ! -e $OUTPUT ]; then mkdir -p $OUTPUT; fi

OUTPNG=$QC/homopolymer_pngs
if [ ! -e $OUTPNG ]; then mkdir -p $OUTPNG; fi

OUTLOG=$QC/homopolymer_logs
if [ ! -e $OUTLOG ]; then mkdir -p $OUTLOG; fi

## Design file (for paired end reads)
     DESIGN_FILE=$PROJ/design_files/qc_design_file.csv

     DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)
     IFS=',' read -ra ARRAY <<< "$DESIGN"

     READ=${ARRAY[0]}
     NAME=${ARRAY[1]}




cd ${ORIG}
# run script
        LOG=$OUTLOG/${NAME}.log
        PNG=$OUTPNG/${NAME}.png
        python $MCPYTHON/identify_homopolymers.py --input ${ORIG}/${READ} --fastq -a --out $OUTPUT/${NAME}.csv --log $LOG --plot $PNG
