#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/cegs/scripts/PBS_LOGS/ase_counts_updated_fusion/
#PBS -l walltime=15:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=80G
#PBS -q bio
#PBS -t 130-189

#### Set Directories
PROJ=/scratch/lfs/mcintyre/cegs
WORK=/scratch/lfs/mcintyre/cegs/ase_pipeline_output
SCRIPTS=$PROJ/scripts

#### Because I am using an PBS Array I am pulling LINE:MV:REP:LANE from an external CSV

DESIGN_FILE=$PROJ/design_files/CEGS_68_lines_no_tech.txt
DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)

IFS=',' read -ra ARRAY <<< "$DESIGN"

LINE=${ARRAY[0]}
MV=${ARRAY[1]}
REP=${ARRAY[2]}

OUTPUT=$WORK/ase_counts_fb551_updated_fusions
if [ ! -e $OUTPUT ]; then mkdir $OUTPUT; fi
echo "`date` $LINE $MV $REP PBS_ARRAYID:$PBS_ARRAYID HOSTNAME:$HOSTNAME"

#### Create LOG directory and start log
LOGS=$OUTPUT/logs 
if [ ! -e $LOGS ]; then mkdir $LOGS; fi

### Concatenate duplicate-removed tech reps for use in sam-compare
cat $PROJ/fastq_split/${LINE}_${MV}${REP}*_uniq.fq  >$TMPDIR/${LINE}_${MV}_${REP}.fq

## Untar the sam files....
##find $WORK/aln_updated_fb551_fusions/ -maxdepth 1 -name "*${LINE}*.gz" -exec tar -zxf {} \;
##cd $WORK/aln_updated_fb530_fusions
##for i in ${LINE}*.tar.gz; do tar -xzf $i; done 

SAM1=$WORK/aln_updated_fb551_fusions/${LINE}_${LINE}_${MV}${REP}_SAMS/${LINE}_${LINE}_${MV}${REP}.sam
SAM2=$WORK/aln_updated_fb551_fusions/${LINE}_w1118${LINE}_${MV}_${REP}_SAMS/${LINE}_w1118${LINE}_${MV}_${REP}.sam

# Run SAM Compare
perl $SCRIPTS/sam-compare-custom_mlm.pl \
    -l 95 \
    -f /scratch/lfs/mcintyre/references/dmel_fb551/fb551_si_fusions.tsv \
    -r /scratch/lfs/mcintyre/references/dmel_fb551/dmel-all-chromosome-r5.30.fasta \
    -q $TMPDIR/${LINE}_${MV}_${REP}.fq \
    -A $SAM1 \
    -B $SAM2 \
    >$OUTPUT/ase_counts_${LINE}_w1118${LINE}_${MV}_${REP}.csv \
    2> $LOGS/ase_counts_${LINE}_w1118${LINE}_${MV}_${REP}.log
