#!/bin/bash
#PBS -N dros_cap3
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=90:00:00
#PBS -l pmem=20gb
#PBS -q bio

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
date
module load cap3

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago
INDIR=/scratch/lfs/mcintyre/trago/dros_test_assembly/normalized_trinity
OUTDIR=/scratch/lfs/mcintyre/trago/dros_test_assembly/cap3

## cat with and outout 10 bp together
cat $INDIR/*.fasta >$INDIR/r324_dros_combined.Trinity.fasta


#### Start cap3 on combined dros 

	READS=$INDIR/r324_dros_combined.Trinity.fasta
	OUTFILE=$OUTDIR/cap3_r324_dros_combined.fasta.out

	cap3 $READS  >$OUTFILE 

