#!/bin/bash
#PBS -N cap3
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=90:00:00
#PBS -l pmem=20gb
#PBS -q bio

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
date
module load cap3

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago
INDIR=$PROJ/trago_output/trag_normalized_trinity_SC
OUTDIR=$PROJ/trago_output/cap3

## cat with and outout 10 bp together
cat $INDIR/Tdu_*.fasta >$OUTDIR/Tdu_norm_combined.Trinity.fasta

#### (1)  Start cap3 on TDU combined

	READS=$OUTDIR/Tdu_norm_combined.Trinity.fasta
	OUTFILE=$OUTDIR/cap3_Tdu_combined.fasta.out

	cap3 $READS  >$OUTFILE 

