#!/bin/bash
#PBS -N cap3_Tpr
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=90:00:00
#PBS -l pmem=20gb
#PBS -q bio

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
date
module load cap3

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago
INDIR=$PROJ/trago_output/trag_normalized_trinity_SC
OUTDIR=$PROJ/trago_output/cap3/TPR

## cat with and outout 10 bp together
cat $INDIR/Tpr_*.fasta >$OUTDIR/Tpr_norm_combined.Trinity.fasta


#### (2) Start cap3 on TPR combined

	READS=$OUTDIR/Tpr_norm_combined.Trinity.fasta
	OUTFILE=$OUTDIR/cap3_Tpr_combined.fasta.out

	cap3 $READS >$OUTFILE

