#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -N filter_sam
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=15:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=160G
#PBS -q bio

#### redo filtering of sam files for Tdu rep 3 reads aligned to TPR


module load perl 

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago
SCRIPTS=/scratch/lfs/mcintyre/trago/scripts
REF=/scratch/lfs/mcintyre/trago/references
SAM=/scratch/lfs/mcintyre/trago/trago_output/aln_parents_to_consensed

OUTPUT=$PROJ/trago_output/filtered_parent_sam_files_TPR

#### Create LOG directory
LOGS=$OUTPUT/logs

#### filter sam file of parental reads aligned to TPR with TPR_tdu bed file
perl $SCRIPTS/sam-filter-by-bed.pl \
    -b $REF/TPR-tdu_overlaps_WRT_orthologs.bed \
    -s $SAM/Tdu_3_uniq_2_TPR.sam \
    >$OUTPUT/Tdu_3_uniq_2_TPR_filter_for_Tms.sam \
    2> $LOGS/Tdu_3_uniq_2_TPR_filter_for_Tms.log


