#!/bin/bash
#PBS -N diabetes-g
#PBS -M anazarian@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /bio/mcintyre/diabetes/PBS_LOGS
#PBS -o Diabetes-gunzip.log
#PBS -j oe
#PBS -l nodes=1:ppn=2
#PBS -l walltime=100:00:00
#PBS -l pmem=10gb
#PBS -q bio
#####PBS -t 1,2%1

#unzip fastqc.gz files

PROJ=/bio/mcintyre/diabetes
DATAIN=$PROJ/PC2009
####OUT=$PROJ/unzipped

cd $DATAIN

## output a list of files and step through that list.

ls *.gz > $PROJ/list-fastqgz-files-2.txt

#####ls > $PROJ/list_fastqgz_files.txt 

for FILE in {1..6074} #there are 6074 files in the list
do

DESIGN=$(cat $PROJ/list-fastqgz-files-2.txt | head -n $FILE | tail -n 1)  #steps through list-fastqgz-files-2.txt by row

gunzip $DESIGN 

done

