#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m ae
#PBS -r n
#PBS -l walltime=144:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=120gb
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -j oe
#PBS -q bigmem
#PBS -t 7-9

### 3 parents and 3 reps per parent = 9
     ## 1-3 are Tdu
     ## 4-6 are Tpo
     ## 7-9 are Tpr

## mpileups for Tpr reads aligned to Tdu and Tpr

module load samtools/1.2

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago

#### Because I am using an PBS Array I am pulling LINE from an external txt file
DESIGN_FILE=$PROJ/design_files/trago_spec_only_with_capitals_reps.txt
DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
IFS=',' read -ra ARRAY <<< "$DESIGN"

SP_CAP=${ARRAY[0]}
SP=${ARRAY[1]}
REP=${ARRAY[2]}

for i in TDU TPR
    do  
      REF=$PROJ/references/${i}_consensed_contigs_500-15k.fasta

      SAM=$PROJ/trago_output/filtered_parent_sam_files/${SP}_${REP}_unq_2_${i}_4_Tms_commonID.sam

#### Create OUTPUT directory if needed.
      OUTPUT=${PROJ}/trago_output/filtered_parent_sam_files/mpileups
      if [ ! -e $OUTPUT ]; then mkdir -p $OUTPUT; fi

#### Create LOG directory and start log
      LOGS=$OUTPUT/logs 
      if [ ! -e $LOGS ]; then mkdir $LOGS; fi
      MYLOG=$LOGS/${SP}_${REP}_2_${i}_mpileup.log

#### Convert SAM to BAM
      BAM=$PROJ/trago_output/filtered_parent_sam_files/mpileups/${SP}_${REP}_unq_2_${i}_4_Tms_commonID

      echo `date`": Starting SAM to BAM conversion" > $MYLOG
      samtools view -ut $REF.fai -o $BAM.bam $SAM 2>>$MYLOG 
      samtools sort -m 10000000000 $BAM.bam $BAM.sorted 2>>$MYLOG
      samtools index $BAM.sorted.bam  >>$MYLOG
      echo `date`": Finished SAM to BAM conversion" >> $MYLOG

#### Make mpileup
      PILEUP=$OUTPUT/${SP}_${REP}_unq_2_${i}_4_Tms_commonID.mpileup

      printf "`date` $SP PBS_ID:$PBS_ARRAYID HOSTNAME:$HOSTNAME \n\n" >> $MYLOG

      echo `date`": Generating pileup" >> $MYLOG

      samtools mpileup -d 10000000000 -f $REF $BAM.sorted.bam  > $PILEUP 2>> $MYLOG

      echo `date`": Finished" >> $MYLOG

    done
