#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900mb
#PBS -t 1-9
     ## 1-3 are Tdu
     ## 4-6 are Tpo
     ## 7-9 are Tpr

module load python/2.7.3 

PROJ=/scratch/lfs/mcintyre/trago
LOGS=$PROJ/trago_output/aln_parents_to_consensed/aln_logs
SCRIPTS=/scratch/lfs/mcintyre/python.git

for J in TDU TPO TPR 
do

        DESIGN_FILE=$PROJ/design_files/trago_spec_only_with_capitals_reps.txt
        DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)

        IFS=',' read -ra ARRAY <<< "$DESIGN"

        SP_CAP=${ARRAY[0]}
        SP=${ARRAY[1]}
        REP=${ARRAY[2]}

        echo "$SP" "$REP"        

        MYLOG=$LOGS/summary_${SP}_${REP}_2_${J}.log    
        if [ -s $LOGS/${SP}_${REP}_2_${J}_bowtie.log ]
        then
	    echo "Parsing log files"
            python $SCRIPTS/logParser.py \
                -bowtie $LOGS/${SP}_${REP}_2_${J}_bowtie.log \
                -last $LOGS/${SP}_${REP}_2_${J}_LAST.log \
                -treatment $SP $REP \
                -o $LOGS/aln_summary_${SP}_${REP}_2_${J}.csv
        fi

done
