#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900mb

module load python/2.7.3 

PROJ=/scratch/lfs/mcintyre/trago
OUTPUT=$PROJ/trago_output/aln_hybrids_to_combined_orthos
LOGS=$OUTPUT/aln_logs
SCRIPTS=$PROJ/scripts

for I in {1..6}
do
    DESIGN_FILE=$PROJ/design_files/trago_hybrids_with_reps.txt
    DESIGN=$(sed -n "${I}p" $DESIGN_FILE)

    IFS=',' read -ra ARRAY <<< "$DESIGN"

    SP=${ARRAY[0]}
    REP=${ARRAY[1]}
    
    if [ -s $LOGS/${SP}_${REP}_2_combo_bowtie.log ]
    then
        python ${SCRIPTS}/logParser.py \
            -bowtie $LOGS/${SP}_${REP}_2_combo_bowtie.log \
            -last $LOGS/${SP}_${REP}_2_combo_LAST.log \
            -treatment $SP $REP \
            -o $OUTPUT/aln_summary_${SP}_${REP}_combined_ortho_`date +%Y%m%d`.csv
    fi

done
