#!/bin/bash 
#PBS -N diabetes
#PBS -M anazarian@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /bio/mcintyre/diabetes/PBS_LOGS
#PBS -o Diabetes-run-fastqc.log
#PBS -j oe
#PBS -l nodes=1:ppn=2
#PBS -l walltime=50:00:00
#PBS -l pmem=10gb
#PBS -q bio

module load fastqc

#generate fastqc files

PROJ=/bio/mcintyre/diabetes
DATAIN=$PROJ/PC2009
OUT=$PROJ/outfiles/fastqc


cd $DATAIN

## output a list of files and step through that list.

ls  > $PROJ/design_files/list_diabetes_fastq_files.txt 

for FILE in {1..10048} #there are 10048 files in the list
do
	DESIGN=$(sed -n "${FILE}p" $PROJ/design_files/list_diabetes_fastq_files.txt)  #steps through list_diabetes_fastq_files.txt by row

	fastqc $DESIGN --outdir=$OUT
done
