#!/bin/bash
#PBS -M fnew@ufl.edu
#PBS -m n
#PBS -N TragoPosBiasTrim
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/posBiasTrim/
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=12gb
#PBS -t 1

module load python 

#Set directories
PROJ=/scratch/lfs/mcintyre/trago
ORIG=$PROJ/trago_outfiles_AN/cutadapt
OUTDIR=$PROJ/qc/posBiasTrim_files
OUTLOG=$PROJ/qc/posBiasTrim_logs

if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi
if [ ! -e $OUTLOG ]; then mkdir -p $OUTLOG; fi


#Pull info from design files

DESIGN_FILE=$PROJ/design_files/list_fq_files_diploids_trimmed.txt

DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
#IFS=',' read -ra ARRAY <<< "$DESIGN"

#GENO=${ARRAY[0]}
#BARCODE=${ARRAY[1]}
#LANE=${ARRAY[2]}
#READ=${ARRAY[3]}
#ADAPTER=${ARRAY[4]}
#TRIM=${ARRAY[5]}

NAME=`basename "$DESIGN" .fq`
#${GENO}_${BARCODE}_${LANE}_${READ}_${ADAPTER}_${TRIM}
LOG=$OUTLOG/${NAME}.log
     
python $PROJ/scripts/position_bias_v3.py  -i $ORIG/$NAME.fq -o $OUTDIR/$NAME.csv -g $LOG
