#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/cegs/scripts/PBS_LOGS/
#PBS -l walltime=2:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=10gb
#PBS -t 1-6

module load python/2.7.3

## Set Directories
PROJ=/scratch/lfs/mcintyre/trago
DATAIN=$PROJ/outfiles/trimmomatic_cat
OUTDIR=$PROJ/trago_output

OUT=$OUTDIR/duplicate_summary_trago_cat.csv

echo "Total_Seq,Uniq_Seq,Per_Uniq" > $OUTDIR/$OUT

## PBS Array to pull in SPECIES  and READ
DESIGN_FILE=$DATAIN/trago_spec_read_list.txt
DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
IFS=',' read -ra ARRAY <<< "$DESIGN"

SPECIES=${ARRAY[0]}
READ=${ARRAY[1]}

cp $DATAIN/${SPECIES}_cat_${READ}_001_trimmomatic_paired.fq $TMPDIR/${SPECIES}_${READ}.fq

$PROJ/scripts/count_total_uniq_fq.py -i $TMPDIR/${SPECIES}_${READ}.fq -o $OUTDIR/${SPECIES}_${READ}_uniq.txt -t $OUTDIR/${SPECIES}_${READ}_table_uniq.txt

cd $OUTDIR
TOTAL=`awk '{if(/^total/) print $5}' ${SPECIES}_${READ}_uniq.txt`
UNIQ=`awk '{if(/^#/) print $5}' ${SPECIES}_${READ}_uniq.txt`
PERCENT=`awk '{if(/^percent/) print $4}' ${SPECIES}_${READ}_uniq.txt`
echo "${SPECIES},${READ},${TOTAL},${UNIQ},${PERCENT}" >> $OUTDIR/$OUT
