#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -N fa2bed
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=6gb

module load python

PROJ=/scratch/lfs/mcintyre/trago
REF=$PROJ/references

for i in TPO 
do

python $PROJ/scripts/fasta2bed.py -f $REF/${i}_consensed_contigs_500-15k.fasta -o $REF/${i}_consensed_contigs_500-15k.bed -g $REF/logs/${i}_consensus_sequences.log

done

