#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -N underbar
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=15:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=160G
#PBS -q bio
#PBS -t 1

## 2 hybrids * 3 reps = 6

module load python

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago

OUTPUT=$PROJ/original_data_w_underbar

#### Using SGE Array to pull in species from external file
    DESIGN_FILE=$PROJ/design_files/trago_hybrids_with_reps.txt
    DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)

    IFS=',' read -ra ARRAY <<< "$DESIGN"

    SP=${ARRAY[0]}
    REP=${ARRAY[1]}

cd $PROJ/original_data/trago-tetraploids/Sample_${SP}${REP}/test

     for i in *.fastq 
     do
          python $PROJ/scripts/fix_fastq_files_v2.py -i $i -o $OUTPUT/$i 
     done


