#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -N sam_Tms
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=15:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=160G
#PBS -q bio
#PBS -t 5,6

## Tm hybrid (1-3) is cross of Tdu and Tpo
## Tms hybrid (4-6) is cross of Tdu and Tpr

module load python/2.7.3 

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago
SCRIPTS=/scratch/lfs/mcintyre/python.git

OUTPUT=$PROJ/trago_output/ase_counts 
if [ ! -e $OUTPUT ]; then mkdir $OUTPUT; fi

#### Create LOG directory
LOGS=$OUTPUT/logs
if [ ! -e $LOGS ]; then mkdir $LOGS; fi

#### Using SGE Array to pull in species (all caps and not)  from external csv
    DESIGN_FILE=$PROJ/design_files/trago_hybrids_with_reps.txt
    DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)

    IFS=',' read -ra ARRAY <<< "$DESIGN"

    SP=${ARRAY[0]}
    REP=${ARRAY[1]}

### Concatenate reads for use in sam-compare
cat ${PROJ}/original_data/trago-tetraploids/Sample_Tms${REP}/Tms${REP}_*.fastq | sed 's/ /_/g' > $TMPDIR/Tms_${REP}.fastq

    READS=$TMPDIR/Tms_${REP}.fastq
    
    ## Doing Tms so select TDU and TPR alignments for comparing
    SAMA=$PROJ/trago_output/filtered_hybrid_sam_files/Tms_${REP}_uniq_2_TDU_filter_commomID.sam
    SAMB=$PROJ/trago_output/filtered_hybrid_sam_files/Tms_${REP}_uniq_2_TPR_filter_commomID.sam 

    # Run SAM Compare
    python $SCRIPTS/sam_compare.py \
	-d \
        -l 100 \
        -f $PROJ/references/TDU_tpr_bed_for_sam_compare.bed \
        -q $READS \
        -A $SAMA \
        -B $SAMB \
        -c $OUTPUT/ase_counts_Tms_${REP}_2_Tdu_Tpr.csv \
        -t $OUTPUT/ase_totals_Tms_${REP}_2_Tdu_Tpr.csv \
        -g $LOGS/ase_counts_Tms_${REP}_2_Tdu_Tpr.log
