#!/bin/bash
#PBS -M lawrence@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=12gb
#PBS -t 1-3

module load python

#Set directories

PROJ=/scratch/lfs/mcintyre/trago
INDIR=/scratch/lfs/mcintyre/trago/trago_output/cap3
OUTDIR=/scratch/lfs/mcintyre/trago/trago_output/cap3
#Pull info from design files

DESIGN_FILE=$PROJ/design_files/trago_spec_only_with_capitals.txt

DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
IFS=',' read -ra ARRAY <<< "$DESIGN"

SP_CAP=${ARRAY[0]}
SP=${ARRAY[1]}

python $PROJ/scripts/filter_contigs_by_length_500bp_srl5.py \
    -i $INDIR/${SP_CAP}/${SP}_norm_combined.Trinity.fasta.cap.contigs \
    -o $OUTDIR/${SP_CAP}/${SP}_contigs_greater_500.fasta

python $PROJ/scripts/filter_contigs_by_length_500bp_srl5.py \
    -i $INDIR/${SP_CAP}/${SP}_norm_combined.Trinity.fasta.cap.singlets \
    -o $OUTDIR/${SP_CAP}/${SP}_singles_greater_500.fasta
