#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/aln_2_ortho
#PBS -l walltime=120:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=100gb
#PBS -q bio


module load bowtie/0.12.9
module load last/247
module load python/2.7.3

#### Store number of processors used -- i.e. number of files to split into to run LAST
    NUMPROCS=4

#### Set directories and variables
    PROJ=/scratch/lfs/mcintyre/trago
    OUTPUT=/scratch/lfs/mcintyre/trago/aln_test/underbar

#### Set Different References
    REF=$PROJ/references/Tdu_common_ortho_pipe
    LASTREF=$PROJ/references/Tdu_common_ortho_pipe

#### Create LOG directory and start log
    LOGS=$OUTPUT/job_logs              #script log information
    ALN_ERROR_LOG=$LOGS/size_errors.txt
    if [ ! -d $LOGS ]; then mkdir -p $LOGS; fi

    MYLOG=$LOGS/test_to_Tdu_ortho.log
    printf "`date` SGE_ID:$PBS_ARRAYID HOSTNAME:$HOSTNAME \n\n" > $MYLOG

    ALNLOGS=$OUTPUT/aln_logs       
    if [ ! -d $ALNLOGS ]; then mkdir -p $ALNLOGS; fi


#### for each species, combine R1 and R2 (treating as single end) and lanes (reps separate)
    cat ${PROJ}/original_data_w_underbar/test_R*_with_underbar.fastq > $TMPDIR/test_underbar.fastq


#### FUNCTIONS FOR ALIGNMENT PIPELINE ####

#### Start alignment pipeline
    printf  '<----------------- STARTING  SE alignment for ${SP}_${REP} [`date`] ----------------->'
    READS=$TMPDIR/test_underbar.fastq

#### If empty stop early

    if [ ! -s $READS ]
    then
        echo "WARNING: Input File is empty terminating early, [`date`]" >>$MYLOG
        echo "Script complete, [`date`]" >>$MYLOG
        exit
    fi

#### Determine my quality FASTQ score type
        qual=`python /scratch/lfs/mcintyre/python.git/identify_quality.py -i $READS`
        if [ $qual == 'phred64' ];
        then
            # set to old illumina quality scores phred64/solexa 1.3
            btqual='--phred64-quals'
            lastqual='3'
        else
            # change to sanger format which is what all new illumina data is
            btqual='--phred33-quals'
            lastqual='1'
        fi

cd $TMPDIR

#### run bowtie uniq
    echo "START Single End bowtie [`date`]" >>$MYLOG
    bowtie -S \
           $btqual \
           --best \
           --tryhard \
           --strata \
           --chunkmbs 1024 \
           -p $NUMPROCS \
           -m 1 \
           -v 3 \
           --un $PROJ/aln_test/underbar/test_unaln_bt.fq \
           --max $PROJ/aln_test/underbar/test_ambig_bt.fq \
           $REF \
           $READS \
           2>$ALNLOGS/test_2_Tdu_bowtie.log \
           > $PROJ/aln_test/underbar/test_aln_bt.sam \
           2>>$MYLOG
        echo "FINISH Single End bowtie [`date`]" >>$MYLOG

k
