#!/bin/bash
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/aln_2_lucas_consensed_contigs
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=40gb
#PBS -q bigmem

module load last/531
module load python/2.7.3


## Set directories
    PROJ=/scratch/lfs/mcintyre/trago
    ORIG=$PROJ/original_data
    INPUT=$PROJ/trago_output/test_aln_bowtie_last
    OUTPUT=$PROJ/trago_output/test_aln_bowtie_last531
    LASTREF=$PROJ/references/TPR_consensed_contigs_500-15k_last531

#### Create LOG directory and start log
    LOGS=$OUTPUT/job_logs       

    MYLOG=$LOGS/Tdu_1_consensus.log

    cat $INPUT/Tdu_1_unaln_bt.fq  $INPUT/Tdu_1_ambig_bt.fq > $TMPDIR/Tdu_1.fq
    READS=$TMPDIR/Tdu_1.fq

    cd $TMPDIR 

#### LAST all
    lastal \
        -l 25 \
        -Q 1 \
        $LASTREF \
        $READS \
        2>>$MYLOG \
        >$OUTPUT/Tdu_1_last.maf 

    # Convert MAF to SAM
    maf-convert.py sam $OUTPUT/Tdu_1_last.maf > $OUTPUT/Tdu_1_last.sam 2>>$MYLOG 
