#!/bin/bash
#PBS -N Trago
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /scratch/lfs/mcintyre/trago/scripts/PBS_LOGS/
#PBS -j oe
#PBS -l nodes=1:ppn=6
#PBS -l walltime=1:00:00
#PBS -l pmem=5gb
#PBS -q bio
#PBS -t 1-3

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
module load trinity

#### Set Directories
PROJ=/scratch/lfs/mcintyre/trago
INDIR=$PROJ/Tragopogon_Normalized_Trinity_SC

#### Because I am using an Array I am pulling SPECIES from an external file 

DESIGN_FILE=$PROJ/trago_spec_only.txt
SPECIES=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)

LOGS=$INDIR/logs
MYLOG=$LOGS/${SPECIES}_trinity_stats.log

### cd to folder with trinity output 
cd $INDIR

#### RUN trinity stats 
TrinityStats.pl ${SPECIES}_dir_denovTrinityOutput.Trinity.fasta > Trinity_${SPECIES}_stats.txt 
