#!/bin/bash
#PBS -q bio
#PBS -M ammorse@ufl.edu
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900M

### consolidate csv files for assessing duplicates for each fq file into 1 for diploids, 1 for trimmed diploids and 1 for tetraploids

#### Set Directories
PROJ=/bio/mcintyre/trago
TRIM=$PROJ/outfiles/cutadapt/duplicates
UNTRIM=$PROJ/outfiles/fastqc/diploids/duplicates
TETS=$PROJ/outfiles/fastqc/tetraploids/duplicates

cd $TRIM
tail +1 * >trago_duplicates_dips_trimmed.csv

cd $UNTRIM
tail +1 * > trago_duplicates_dips_untrimmed.csv

cd $TETS 
tail +1 * > trago_duplicates_tets.csv 
