#!/bin/bash
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -r n
#PBS -q bio
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900M
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/fastqc_tetraploid
#PBS -t 1-6
#54

#### Set Directories
PROJ=/bio/mcintyre/trago 
WORK=$PROJ/outfiles/fastqc/tetraploids/Sample_Tms3
HTMLDOC=/home/jfear/bin/htmldoc

PDF=$PROJ/outfiles/fastqc_summary/tetraploids/fastqc_tetraploids_pdf

if [ ! -e $PDF ]; then mkdir -p $PDF; fi

#### Because I am using an PBS Array I am pulling LINE:MV:REP from an external CSV with all possible combinations
DESIGN_FILE=$PROJ/scripts/fastqc/design_files/trago_Sample_Tms3_design_file.csv
DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)

IFS=',' read -ra ARRAY <<< "$DESIGN"

NAME=${ARRAY[0]}
BC=${ARRAY[1]}
LANE=${ARRAY[2]}
RUN=${ARRAY[3]}

$HTMLDOC --webpage --fontsize 7 --browserwidth 800 --header . $WORK/${NAME}_${BC}_${LANE}_${RUN}_001_fastqc/fastqc_report.html -f $PDF/${NAME}_${BC}_${LANE}_${RUN}_001.pdf 
