#!/bin/bash 
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -r n
#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900M
#PBS -j oe
#PBS -o /bio/mcintyre/trago/outfiles/PBS_LOGS/fastqc/

#generate fastqc files

PROJ=/bio/mcintyre/trago
DATAIN=$PROJ/outfiles/fastqc/diploids
PDF=$PROJ/outfiles/fastqc_pdfs/diploids
HTMLDOC=/home/jfear/bin/htmldoc

if [ ! -e $PDF ]; then mkdir -p $PDF; fi

cd $DATAIN

## output a list of files and step through that list.

ls *.zip | cut -f1 -d'.'  > $PROJ/list_fastqc_diploids.txt 

for FILE in {1..54} 
do
	DESIGN=$(sed -n "${FILE}p" $PROJ/list_fastqc_diploids.txt)  #steps through list_fq_files_diploids.txt by row

	$HTMLDOC --webpage --fontsize 7 --browserwidth 800 --header . $DESIGN/fastqc_report.html -f $PDF/${DESIGN}.pdf 
done
