#!/bin/bash
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=4
#PBS -l pmem=1gb
#PBS -t 1-6

## note that there are 6 fastq files for each trago species

#### Set Directories
PROJ=/bio/mcintyre/trago
FILES=$PROJ/trago-tetraploids
OUTDIR=$PROJ/trago-tetraploids/count_fq


#### I am using an SGE Array (pulls out each name from the file and calls it 'design')

## Tm1 fastq files:

DESIGN_FILE=$PROJ/outfiles/fastqc/tetraploids/design_files/list_trago_tetra_Tm1_fq.txt 
DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)  #steps through list_trago_tetra_Tm1_fq.txt by row

cd $FILES/Sample_Tm1

for f in $FILES/Sample_Tm1
do
    grep '@HWI' $FILES | wc -l > /bio/mcintyre/trago/trago-tetraploids/count_fq/fq_cnt_$DESIGN.txt
done


## Tm2 fastq files:

DESIGN_FILE=$PROJ/outfiles/fastqc/tetraploids/design_files/list_trago_tetra_Tm2_fq.txt
DESIGN=$(cat $DESIGN_FILE | head -n $PBS_ARRAYID | tail -n 1)  #steps through list_trago_tetra_Tm2_fq.txt by row

cd $FILES/Sample_Tm2

for f in $FILES/Sample_Tm2
do
    grep '@HWI' $FILES | wc -l > /bio/mcintyre/trago/trago-tetraploids/count_fq/fq_cnt_$DESIGN.txt
done

