#!/bin/bash 
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/PBS_LOGS/fastqc_trimmed/
#PBS -l walltime=2:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1Gb

#generate fastqc files

PROJ=/bio/mcintyre/trago
DATAIN=$PROJ/outfiles/cutadapt
OUT=$PROJ/outfiles/cutadapt/fastqc

module load fastqc

cd $DATAIN

## output a list of files and step through that list.

ls  > $PROJ/list_fq_files_diploids_trimmed.txt 

for FILE in {51..54} #there are 54 files in the list
do
	DESIGN=$(sed -n "${FILE}p" $PROJ/list_fq_files_diploids_trimmed.txt)  #steps through list_fq_files_diploids.txt by row

	fastqc $DESIGN --outdir=$OUT
done
