#!/bin/bash
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=10gb

PROJ=/bio/mcintyre/trago
DATAIN=$PROJ/trago_data
OUTDIR=$PROJ/outfiles/illumina_blast/fasta

if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

cd $DATAIN 

for FILE in *.fastq
do
    NAME=`basename $FILE .fastq`

    perl $PROJ/scripts/fastqc/fastq2fasta.pl $NAME.fastq > $OUTDIR/$NAME.fasta

done
