#!/bin/bash 
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/
#PBS -l walltime=3:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1Gb

module load fastqc/0.10.1

#Set directories.

PROJ=/bio/mcintyre/trago
DATAIN=$PROJ/trago-tetraploid/Sample_Tm1
LISTS=$PROJ/scripts/fastqc
OUT=$PROJ/outfiles/fastqc/tetraploids/Sample_Tm1/fastqc
FILE=$LISTS/list_fq_files_tetraploid_Sample_Tm1.txt

if [ ! -e $OUTPUT ]; then mkdir -p $OUTPUT; fi

## Output a list of files and step through that list. Create fastcq files.

cd $DATAIN

ls *.fastq  > $LISTS/list_fq_files_tetraploid_Sample_Tm1.txt

for $FILE in {1..6} #there are 6 files in the list
do
        DESIGN=$(sed -n "${FILE}p" $DATAIN/list_fq_files_tetraploid_Sample_Tm1.txt)  #steps through list_fq_files_tetraploid_Sample_Tm1.txt by row

        fastqc $DESIGN --outdir=$OUT
done
