#!/bin/bash
#PBS -q bio
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/fastqc_tetraploid/
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=900M

#### Set Directories
PROJ=/bio/mcintyre/trago
INDIR=$PROJ/outfiles/fastqc/tetraploids/fastqc_files
FASTQC=$PROJ/scripts/fastqc/fastqc_pass-fail_list_rlb.pl
OUTDIR=$PROJ/outfiles/fastqc_summary/tetraploids/round2

if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

echo "Sample_id,basic_stats,base_qual,seq_qual,base_content,base_GC,seq_GC,base_N,seq_length,seq_dup,seq_overrep,kmer,percent_pass" > $OUTDIR/fastqc_pass-fail_summary_dip_untrim.csv

cd $INDIR

for SAMPLE in $( find ./ -maxdepth 1 -type d -print | cut -d'/' -f2)
do

    FILE=$INDIR/$SAMPLE/summary.txt

    perl $FASTQC $SAMPLE $FILE  >> $OUTDIR/fastqc_pass-fail_summary_dip_untrim.csv

done;
