#!/bin/bash
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/trago/scripts/fastqc/PBS_LOGS/
#PBS -l walltime=5:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=4gb

module load python

PROJ=/bio/mcintyre/trago
DATAIN=$PROJ/outfiles/cutadapt
OUTDIR=$PROJ/outfiles/cutadapt/duplicates

if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

cd $DATAIN 

for FQ in $(ls *.fq)
do

    NAME=`basename $FQ .fq`

    python $PROJ/scripts/fastqc/count_total_uniq_fq.py -i $FQ -o $OUTDIR/$NAME.csv

done
