#!/bin/bash
#PBS -M polvadore@ufl.edu
#PBS -m n
#PBS -q bio
#PBS -r n
#PBS -j oe
#PBS -o /bio/mcintyre/vermerris_sorghum/scripts/PBS_LOGS/fastqc/
#PBS -l walltime=1:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb

PROJ=/bio/mcintyre/vermerris_sorghum
DATAIN=$PROJ/fastqc
OUTDIR=$PROJ/fastqc_summary/files

if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

cd $DATAIN 

for DIR in $( find ./ -maxdepth 1 -type d | cut -f2 -d'/')
do
    cd $DATAIN/$DIR

    NAME=`basename $DIR _fastqc`

    perl $PROJ/scripts/fastqc_stats_v2_jmf.pl $NAME $OUTDIR

done
