#!/bin/bash
#PBS -N Drosophila
#PBS -M anazarian@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /bio/mcintyre/trago/dros_outfiles/PBS_LOGS/blast-dros-dros
#PBS -o Drosophila-Drosophila-all-transcripts-5-51-H.log
#PBS -j oe
#PBS -l nodes=1:ppn=2
#PBS -l walltime=2:00:00
#PBS -l pmem=5gb
#PBS -q bio
#####PBS -t 1

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
date
module load ncbi_blast

#### Set Directories
WORK=/bio/mcintyre
PROJ=trago

OUTDIR=$WORK/$PROJ/dros_outfiles
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

INDIR=$OUTDIR/references

#####INDIR=$WORK/$PROJ/dros_outfiles/references
#####start log
LOGS=$OUTDIR/LOGS/blast-dros-dros 		#script log information
if [ ! -e $LOGS ]
then
    mkdir -p $LOGS
fi


OUT1=$OUTDIR/blast-dros-dros
if [ ! -e $OUT1 ]; then mkdir -p $OUT1; fi


MYLOG=$LOGS/Drosophila-Drosophila-all-transcripts-5-51-H.log
printf "`date` \n\n" > $MYLOG

######makeblastdb -in dmel-all-transcript-r5.30.fasta -dbtype 'nucl' -out dmel-all-transcript-r5.30_BLAST

#####REF=$WORK/$PROJ/dros_outfiles/references/dmel-all-chromosome-r5.30_BLAST

REF=$INDIR/dmel-all-transcript-r5.51_BLAST
READS=$INDIR/dmel-all-transcript-r5.51.fasta
OUTFILE=$OUT1/Drosophila-Drosophila-all-transcripts-5-51-H-results.tsv

blastn -db $REF -query $READS -outfmt 7 > $OUTFILE

2>>$MYLOG
