#!/bin/bash
#PBS -N Drosophila
#PBS -M anazarian@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /bio/mcintyre/trago/outfiles/PBS_LOGS/blast
#PBS -o Drosophila_trinity_blast_uniprot_DROM_1.2.log
#PBS -j oe
#PBS -l nodes=1:ppn=2
#PBS -l walltime=5:00:00
#PBS -l pmem=5gb
#PBS -q bio
#######PBS -t 1

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
date
module load ncbi_blast

#### Set Directories
WORK=/bio/mcintyre
PROJ=trago
INDIR=$WORK/$PROJ/outfiles/blast/uniprot
OUTDIR=$WORK/$PROJ/outfiles
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

#####start log
LOGS=$OUTDIR/LOGS/blast 		#script log information
if [ ! -e $LOGS ]
then
    mkdir -p $LOGS
fi

MYLOG=$LOGS/Drosophila_trinity_blast_uniprot_DROM_1.2.log
printf "`date` \n\n" > $MYLOG

######makeblastdb -in uniprot_sprot.fasta -dbtype 'prot' -out uniprot_sprot_BLAST

REF=$INDIR/uniprot_DROME_BLAST
READS=$INDIR/best_candidates.eclipsed_orfs_removed_2.pep
OUTFILE=$INDIR/trinity_blast_uniprot_DROM_1.2_results.tsv

blastp -query $READS -db $REF -num_threads 2 -outfmt 7 -out $OUTFILE

######-max_target_seqs 1

2>>$MYLOG
