#!/bin/bash
#PBS -N Drosophila
#PBS -M anazarian@ufl.edu
#PBS -m n
#PBS -r n
#PBS -o /bio/mcintyre/trago/outfiles/PBS_LOGS/trinity
#PBS -o Drosophila-trinity.log
#PBS -j oe
#PBS -l nodes=1:ppn=6
#PBS -l walltime=20:00:00
#PBS -l pmem=25gb
#PBS -q bio
#PBS -t 1%1

#### This specifies to use the directory I submitted the script from
cd $PBS_O_WORKDIR
date
module load trinity

#### Set Directories
WORK=/bio/mcintyre
PROJ=trago
INDIR=$WORK/$PROJ/outfiles/trimmomatic_concatfiles
OUTDIR=$WORK/$PROJ/outfiles
if [ ! -e $OUTDIR ]; then mkdir -p $OUTDIR; fi

#### Because I am using an Array I am pulling LINE:MV:REP from an external CSV with all possible combinations

DESIGN_FILE=$WORK/$PROJ/dros_biorep_list_2.csv
DESIGN=$(sed -n "${PBS_ARRAYID}p" $DESIGN_FILE)
IFS=',' read -ra ARRAY <<< "$DESIGN"
LINE=${ARRAY[0]}
MV=${ARRAY[1]}
REP=${ARRAY[2]}
LANE1=${ARRAY[3]}
LANE2=`echo $LANE1 | sed 's/\.1/\.2/g'`

#### Create LOG directory and start log
LOGS=$OUTDIR/LOGS/trinity 		#script log information
if [ ! -e $LOGS ]
then
    mkdir -p $LOGS
fi

MYLOG=$LOGS/${LINE}_${MV}_${REP}_${LANE1}_${LANE2}_Drosophila_trinity.log
printf "`date` $LINE $MV $REP $LANE1 $LANE2 SGE_ID:$PBS_ARRAYID HOSTNAME:$HOSTNAME \n\n" > $MYLOG

#####TRINLOG=$LOGS/${LINE}_${MV}_${REP}_${LANE1}_${LANE2}_Drosophila_trinity.log

#### Start Trinity
READS1=$INDIR/${LINE}_${MV}_${REP}_${LANE1}_trimmomatic_paired.fq
READS2=$INDIR/${LINE}_${MV}_${REP}_${LANE2}_trimmomatic_paired.fq
OUT1=$OUTDIR/trinity
if [ ! -e $OUT1 ]
then
    mkdir -p $OUT1
fi

### Start Lane Section in Log
####printf "$LANE\n" >> $MYLOG

export _JAVA_OPTIONS="-Xmx20g"
#### RUN trinity on Paired-end Files
Trinity.pl --seqType fq --JM 18G --left $READS1  --right $READS2 --output $OUT1 --CPU 6 --full_cleanup

2>>$MYLOG
